title: Adam Sneed
logo: /images/Adam_Sneed.png
description: Data Science student seeking a full-time position in a related field where my passion for mathematics, statistics, and coding can make an immediate impact through meaningful data insight. Working over three years in a leadership role, I am eager to use my problem solving and critical thinking strengths in a dynamic, technical work environment.

show_downloads: true
theme: jekyll-theme-minimal
